import { t } from "@lingui/core/macro";
import { Trans } from "@lingui/react/macro";
import { AppLayout } from "@repo/ui/components/AppLayout";
import { Badge } from "@repo/ui/components/Badge";
import { Button } from "@repo/ui/components/Button";
import { Text } from "@repo/ui/components/Text";
import { createFileRoute } from "@tanstack/react-router";
import { AwardIcon, FileTextIcon, PlusIcon, SparklesIcon } from "lucide-react";
import { useState } from "react";
import { FundraiserSideMenu } from "@/shared/components/FundraiserSideMenu";
import { TopMenu } from "@/shared/components/topMenu";
import { api } from "@/shared/lib/api/client";
import { CertificateBatchDetailPane } from "./-components/CertificateBatchDetailPane";
import { CertificateTemplateDetailPane } from "./-components/CertificateTemplateDetailPane";
import { CreateCertificateTemplateDialog } from "./-components/CreateCertificateTemplateDialog";
import { GenerateCertificatesDialog } from "./-components/GenerateCertificatesDialog";

export const Route = createFileRoute("/$slug/fundraiser/certificates")({
  component: CertificatesPage
});

function batchStatusVariant(status: string) {
  switch (status) {
    case "Pending": return "neutral";
    case "Processing": return "info";
    case "Completed": return "success";
    case "Failed": return "destructive";
    default: return "outline";
  }
}

export default function CertificatesPage() {
  const { data: batches, isLoading: batchesLoading } = api.useQuery("get", "/api/fundraiser/certificates/batches");
  const { data: templates, isLoading: templatesLoading } = api.useQuery("get", "/api/fundraiser/certificates/templates");
  const [activeTab, setActiveTab] = useState<"batches" | "templates">("batches");
  const [showGenerateDialog, setShowGenerateDialog] = useState(false);
  const [showCreateTemplateDialog, setShowCreateTemplateDialog] = useState(false);
  const [selectedBatchId, setSelectedBatchId] = useState<string | null>(null);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);

  return (
    <>
      <FundraiserSideMenu />
      <AppLayout
        topMenu={<TopMenu breadcrumbs={[{ label: t`Certificates` }]} />}
        title={t`Tax Certificates`}
        subtitle={t`Generate and manage Section 18A tax certificates for donors.`}
      >
        {/* Tabs */}
        <div className="mb-4 flex items-center gap-2 border-b border-border">
          <button
            type="button"
            className={`px-4 py-2 text-sm font-medium ${activeTab === "batches" ? "border-b-2 border-foreground text-foreground" : "text-muted-foreground hover:text-foreground"}`}
            onClick={() => setActiveTab("batches")}
          >
            <Trans>Batches</Trans>
          </button>
          <button
            type="button"
            className={`px-4 py-2 text-sm font-medium ${activeTab === "templates" ? "border-b-2 border-foreground text-foreground" : "text-muted-foreground hover:text-foreground"}`}
            onClick={() => setActiveTab("templates")}
          >
            <Trans>Templates</Trans>
          </button>
        </div>

        {/* Batches Tab */}
        {activeTab === "batches" && (
          <>
            <div className="mb-4 flex items-center justify-between">
              <Text className="text-muted-foreground">
                {batches ? t`${batches.length} batches` : t`Loading...`}
              </Text>
              <Button variant="primary" onPress={() => setShowGenerateDialog(true)}>
                <SparklesIcon className="mr-1.5 h-4 w-4" />
                <Trans>Generate certificates</Trans>
              </Button>
            </div>
            {batchesLoading ? (
              <div className="flex items-center justify-center py-12">
                <Text className="text-muted-foreground"><Trans>Loading batches...</Trans></Text>
              </div>
            ) : batches && batches.length > 0 ? (
              <div className="overflow-hidden rounded-lg border border-border">
                <table className="w-full">
                  <thead className="border-border border-b bg-muted/50">
                    <tr>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>Tax Year</Trans></th>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>Status</Trans></th>
                      <th className="px-4 py-3 text-right font-medium text-muted-foreground text-sm"><Trans>Certificates</Trans></th>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>Generated by</Trans></th>
                      <th className="px-4 py-3 text-right font-medium text-muted-foreground text-sm"><Trans>Created</Trans></th>
                    </tr>
                  </thead>
                  <tbody>
                    {batches.map((batch) => (
                      <tr
                        key={String(batch.id)}
                        className="cursor-pointer border-border border-b last:border-b-0 hover:bg-hover-background"
                        onClick={() => setSelectedBatchId(String(batch.id))}
                      >
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-2">
                            <AwardIcon className="h-4 w-4 text-muted-foreground" />
                            <span className="font-medium text-foreground">{batch.taxYear}/{batch.taxYear + 1}</span>
                          </div>
                        </td>
                        <td className="px-4 py-3">
                          <Badge variant={batchStatusVariant(batch.status)}>{batch.status}</Badge>
                        </td>
                        <td className="px-4 py-3 text-right text-muted-foreground">{batch.totalCertificates}</td>
                        <td className="px-4 py-3 text-muted-foreground">{batch.generatedBy}</td>
                        <td className="px-4 py-3 text-right text-muted-foreground">
                          {new Date(batch.createdAt).toLocaleDateString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center rounded-lg border border-dashed border-border py-12">
                <AwardIcon className="mb-3 h-8 w-8 text-muted-foreground" />
                <Text className="mb-2 text-muted-foreground"><Trans>No certificate batches yet</Trans></Text>
                <Text className="text-muted-foreground text-sm"><Trans>Generate your first batch of Section 18A tax certificates.</Trans></Text>
              </div>
            )}
          </>
        )}

        {/* Templates Tab */}
        {activeTab === "templates" && (
          <>
            <div className="mb-4 flex items-center justify-between">
              <Text className="text-muted-foreground">
                {templates ? t`${templates.length} templates` : t`Loading...`}
              </Text>
              <Button variant="primary" onPress={() => setShowCreateTemplateDialog(true)}>
                <PlusIcon className="mr-1.5 h-4 w-4" />
                <Trans>Create template</Trans>
              </Button>
            </div>
            {templatesLoading ? (
              <div className="flex items-center justify-center py-12">
                <Text className="text-muted-foreground"><Trans>Loading templates...</Trans></Text>
              </div>
            ) : templates && templates.length > 0 ? (
              <div className="overflow-hidden rounded-lg border border-border">
                <table className="w-full">
                  <thead className="border-border border-b bg-muted/50">
                    <tr>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>Name</Trans></th>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>Organisation</Trans></th>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>PBO Number</Trans></th>
                      <th className="px-4 py-3 text-left font-medium text-muted-foreground text-sm"><Trans>Default</Trans></th>
                      <th className="px-4 py-3 text-right font-medium text-muted-foreground text-sm"><Trans>Created</Trans></th>
                    </tr>
                  </thead>
                  <tbody>
                    {templates.map((template) => (
                      <tr
                        key={String(template.id)}
                        className="cursor-pointer border-border border-b last:border-b-0 hover:bg-hover-background"
                        onClick={() => setSelectedTemplateId(String(template.id))}
                      >
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-2">
                            <FileTextIcon className="h-4 w-4 text-muted-foreground" />
                            <span className="font-medium text-foreground">{template.name}</span>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-muted-foreground">{template.organisationName ?? "—"}</td>
                        <td className="px-4 py-3 text-muted-foreground">{template.pboNumber ?? "—"}</td>
                        <td className="px-4 py-3">
                          {template.isDefault && <Badge variant="success"><Trans>Default</Trans></Badge>}
                        </td>
                        <td className="px-4 py-3 text-right text-muted-foreground">
                          {new Date(template.createdAt).toLocaleDateString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center rounded-lg border border-dashed border-border py-12">
                <FileTextIcon className="mb-3 h-8 w-8 text-muted-foreground" />
                <Text className="mb-2 text-muted-foreground"><Trans>No templates yet</Trans></Text>
                <Text className="text-muted-foreground text-sm"><Trans>Create a certificate template with your organisation details.</Trans></Text>
              </div>
            )}
          </>
        )}
      </AppLayout>
      <GenerateCertificatesDialog isOpen={showGenerateDialog} onClose={() => setShowGenerateDialog(false)} />
      <CreateCertificateTemplateDialog isOpen={showCreateTemplateDialog} onClose={() => setShowCreateTemplateDialog(false)} />
      {selectedBatchId && (
        <CertificateBatchDetailPane
          batchId={selectedBatchId}
          isOpen={!!selectedBatchId}
          onClose={() => setSelectedBatchId(null)}
        />
      )}
      {selectedTemplateId && (
        <CertificateTemplateDetailPane
          templateId={selectedTemplateId}
          isOpen={!!selectedTemplateId}
          onClose={() => setSelectedTemplateId(null)}
        />
      )}
    </>
  );
}
