import { t } from "@lingui/core/macro";
import { Trans } from "@lingui/react/macro";
import { Badge } from "@repo/ui/components/Badge";
import { Separator } from "@repo/ui/components/Separator";
import { SidePane, SidePaneBody, SidePaneHeader } from "@repo/ui/components/SidePane";
import { Text } from "@repo/ui/components/Text";
import { AwardIcon } from "lucide-react";
import { api } from "@/shared/lib/api/client";

type CertificateBatchDetailPaneProps = Readonly<{
  batchId: string;
  isOpen: boolean;
  onClose: () => void;
}>;

function batchStatusVariant(status: string) {
  switch (status) {
    case "Pending": return "neutral";
    case "Processing": return "info";
    case "Completed": return "success";
    case "Failed": return "destructive";
    default: return "outline";
  }
}

function certStatusVariant(status: string) {
  switch (status) {
    case "Pending": return "neutral";
    case "Generated": return "success";
    case "Failed": return "destructive";
    default: return "outline";
  }
}

function formatCurrency(amount: number) {
  return new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(amount);
}

export function CertificateBatchDetailPane({ batchId, isOpen, onClose }: CertificateBatchDetailPaneProps) {
  const { data: batch, isLoading } = api.useQuery("get", "/api/fundraiser/certificates/batches/{id}", {
    params: { path: { id: batchId } }
  });

  return (
    <SidePane isOpen={isOpen} onOpenChange={(open) => { if (!open) onClose(); }}>
      <SidePaneHeader>
        {batch ? t`Batch — ${batch.taxYear}/${batch.taxYear + 1}` : t`Certificate Batch`}
      </SidePaneHeader>
      <SidePaneBody>
        {isLoading ? (
          <Text className="text-muted-foreground"><Trans>Loading...</Trans></Text>
        ) : batch ? (
          <div className="flex flex-col gap-6">
            {/* Status & Summary */}
            <div className="flex items-center gap-2">
              <Badge variant={batchStatusVariant(batch.status)}>{batch.status}</Badge>
              <Text className="text-muted-foreground text-sm">
                {batch.totalCertificates} <Trans>certificates</Trans>
              </Text>
            </div>

            {/* Details */}
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <Text className="text-muted-foreground"><Trans>Tax Year</Trans></Text>
                <Text className="font-medium">{batch.taxYear}/{batch.taxYear + 1}</Text>
              </div>
              <div>
                <Text className="text-muted-foreground"><Trans>Generated by</Trans></Text>
                <Text className="font-medium">{batch.generatedBy ?? "—"}</Text>
              </div>
              <div>
                <Text className="text-muted-foreground"><Trans>Created</Trans></Text>
                <Text className="font-medium">{new Date(batch.createdAt).toLocaleString()}</Text>
              </div>
              {batch.completedAt && (
                <div>
                  <Text className="text-muted-foreground"><Trans>Completed</Trans></Text>
                  <Text className="font-medium">{new Date(batch.completedAt).toLocaleString()}</Text>
                </div>
              )}
            </div>

            {batch.errorMessage && (
              <div className="rounded-md bg-destructive/10 p-3 text-destructive text-sm">
                {batch.errorMessage}
              </div>
            )}

            <Separator />

            {/* Certificates list */}
            <div>
              <Text className="mb-3 font-medium"><Trans>Certificates</Trans></Text>
              {batch.certificates && batch.certificates.length > 0 ? (
                <div className="flex flex-col gap-2">
                  {batch.certificates.map((cert) => (
                    <div key={String(cert.id)} className="flex items-center justify-between rounded-md border border-border p-3">
                      <div className="flex items-center gap-3">
                        <AwardIcon className="h-4 w-4 text-muted-foreground" />
                        <div>
                          <Text className="font-medium text-sm">{cert.donorName}</Text>
                          <Text className="text-muted-foreground text-xs">
                            <Trans>Receipt</Trans> #{cert.receiptNumber}
                          </Text>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <Text className="font-medium text-sm">{formatCurrency(cert.totalDonated)}</Text>
                        <Badge variant={certStatusVariant(cert.status)}>{cert.status}</Badge>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <Text className="text-muted-foreground text-sm"><Trans>No certificates in this batch.</Trans></Text>
              )}
            </div>
          </div>
        ) : (
          <Text className="text-muted-foreground"><Trans>Batch not found.</Trans></Text>
        )}
      </SidePaneBody>
    </SidePane>
  );
}
