import { FundraiserConfig } from "@/types";

export const INITIAL_CONFIG: FundraiserConfig = {
  id: "tenant-001",
  tenantName: "Thrive Africa",
  title: "Urban Water Resilience 2024",
  subtitle: "Deploying smart-grid water sensors across high-density housing projects.",
  story:
    "Water scarcity is not just a seasonal crisis; it is a systemic challenge. By integrating IoT sensors into existing municipal pipes, we can identify leaks in seconds rather than months.\n\nThis project aims to deploy 500 sensors across the Guguletu district, saving an estimated 1.2 million liters per year. Your contribution directly funds the hardware and local installer training.",
  goal: 45000,
  raised: 28450,
  primaryColor: "#0f766e",
  heroImage:
    "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&q=80&w=1200&h=675",
  active: true,
  terminology: {
    donation: "Gift",
    donor: "Sponsor",
    campaign: "Mission",
    goal: "Target",
  },
  subscriptionPlan: "Pro",
  branches: [
    { id: "b1", name: "Cape Town HQ", location: "Waterfront, CP" },
    { id: "b2", name: "Joburg Hub", location: "Sandton, JHB" },
  ],
  partnerTiers: [
    {
      id: "pt-1",
      name: "Community Partner",
      minCommitment: 5000,
      benefits: ["Homepage logo mention", "Quarterly impact brief", "Local event listing"],
      color: "#a16207",
    },
    {
      id: "pt-2",
      name: "Growth Partner",
      minCommitment: 15000,
      benefits: ["Story-level mentions", "Branded campaign feature", "Quarterly stakeholder walkthrough"],
      color: "#0f766e",
    },
    {
      id: "pt-3",
      name: "Anchor Partner",
      minCommitment: 50000,
      benefits: ["Premier logo placement", "Dedicated impact spotlight", "Annual keynote invitation"],
      color: "#c2410c",
    },
  ],
  partners: [
    {
      id: "p-1",
      name: "EcoFlow Solutions",
      contactPerson: "Alice Rivers",
      email: "alice@ecoflow.com",
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e4/EcoFlow_Logo.svg",
      tierId: "pt-2",
      status: "active",
      totalContributed: 18500,
      joinedDate: "2023-01-15",
      lastContributionDate: "2025-11-21",
    },
    {
      id: "p-2",
      name: "Urban Grid Corp",
      contactPerson: "Mark Sandton",
      email: "mark@urbangrid.co.za",
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Grid_Logo.svg",
      tierId: "pt-1",
      status: "active",
      totalContributed: 6000,
      joinedDate: "2024-02-10",
      lastContributionDate: "2025-09-10",
    },
  ],
  partnerMentions: [
    {
      id: "pm-1",
      partnerId: "p-1",
      quote: "We finally have transparent neighborhood-level impact metrics.",
      context: "Q4 Impact Review",
      highlighted: true,
    },
    {
      id: "pm-2",
      partnerId: "p-2",
      quote: "This program ties every contribution to measurable water savings.",
      context: "Board Presentation",
      highlighted: false,
    },
  ],
  beneficiaryStories: [
    {
      id: "s1",
      name: "The Mthembu Family",
      bio: "Living with intermittent supply for 3 years, the sensor program restored consistent access for their household.",
      goal: 1200,
      raised: 1100,
      image: "https://picsum.photos/seed/mthembu/600/600",
    },
    {
      id: "s2",
      name: "Guguletu Primary",
      bio: "Protecting school facilities from major plumbing leaks through advanced real-time detection.",
      goal: 2500,
      raised: 800,
      image: "https://picsum.photos/seed/creche/600/600",
    },
    {
      id: "s3",
      name: "Sizwe's Micro-Garden",
      bio: "Utilizing saved greywater for sustainable urban farming in the heart of the community.",
      goal: 3000,
      raised: 2100,
      image: "https://picsum.photos/seed/garden/600/600",
    },
  ],
  events: [
    {
      id: "e1",
      title: "Water Walk Gala 2024",
      date: "2024-11-12T18:00:00Z",
      endDate: "2024-11-12T22:00:00Z",
      venue: "V&A Convention Centre",
      address: "Dock Road, Victoria & Alfred Waterfront, Cape Town, 8001",
      description:
        "An evening of live music, donor recognition, and a keynote on urban water resilience. All proceeds fund sensor deployment in Guguletu.",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      volunteerIds: ["vol-1", "vol-2"],
      image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&fit=crop",
      capacity: 200,
      rsvpCount: 147,
      timetable: [
        { id: "tt-1a", time: "18:00", label: "Doors open and welcome drinks" },
        { id: "tt-1b", time: "19:00", label: "Keynote: Water as a Human Right", speaker: "Dr. Sarah Jones" },
        { id: "tt-1c", time: "20:30", label: "Live auction and entertainment" },
      ],
      partnerIds: ["p-1"],
      status: "completed",
      category: "gala",
      contactEmail: "events@thriveafrica.org",
      contactPhone: "+27 21 555 0101",
    },
    {
      id: "e2",
      title: "Community Hackathon",
      date: "2024-12-05T09:00:00Z",
      endDate: "2024-12-05T17:00:00Z",
      venue: "Innovation Hub Guguletu",
      address: "12 NY 1, Guguletu, Cape Town, 7750",
      description:
        "A day-long hackathon for local developers and engineers to prototype smart-water solutions for underserved communities.",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      volunteerIds: ["vol-2"],
      image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=800&fit=crop",
      capacity: 60,
      rsvpCount: 52,
      timetable: [
        { id: "tt-2a", time: "09:00", label: "Registration and team formation" },
        { id: "tt-2b", time: "10:00", label: "Hacking begins" },
        { id: "tt-2c", time: "16:00", label: "Demos and judging", speaker: "Mark Sandton" },
      ],
      partnerIds: ["p-2"],
      status: "completed",
      category: "hackathon",
      contactEmail: "tech@thriveafrica.org",
    },
    {
      id: "e3",
      title: "Impact Stakeholder Dinner",
      date: "2025-01-15T19:30:00Z",
      endDate: "2025-01-15T22:30:00Z",
      venue: "The Silo Hotel",
      address: "Silo Square, Victoria & Alfred Waterfront, Cape Town, 8001",
      description:
        "An intimate dinner presenting Q4 impact data and the 2025 expansion roadmap to anchor partners and government stakeholders.",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=800&fit=crop",
      capacity: 40,
      rsvpCount: 38,
      timetable: [
        { id: "tt-3a", time: "19:30", label: "Welcome and canapes" },
        { id: "tt-3b", time: "20:15", label: "2025 Roadmap Presentation", speaker: "Dr. Sarah Jones" },
      ],
      partnerIds: ["p-1", "p-2"],
      status: "upcoming",
      category: "fundraiser",
      contactEmail: "events@thriveafrica.org",
      contactPhone: "+27 21 555 0101",
    },
  ],
  blogPosts: [
    {
      id: "b1",
      title: "Scaling Smart Sensors in Q4",
      excerpt: "How ultrasonic waves are helping us find water leaks without digging.",
      content: "Technical deep dive into the IoT stack...",
      date: "Oct 28, 2024",
      author: "Dr. Sarah Jones",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=400&h=300&fit=crop",
    },
    {
      id: "b2",
      title: "First 100 Households Secured",
      excerpt: "Milestone reached: Our initial pilot project is now fully operational.",
      content: "Detailed report on deployment...",
      date: "Oct 15, 2024",
      author: "Team Lead",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      image: "https://images.unsplash.com/photo-1544333346-64e4fe1fefe0?q=80&w=400&h=300&fit=crop",
    },
    {
      id: "b3",
      title: "Why Data Matters for Water",
      excerpt: "Transparent metrics are changing how we fund infrastructure.",
      content: "An editorial on transparency...",
      date: "Oct 05, 2024",
      author: "Thrive Editor",
      campaignId: "camp-water-resilience",
      image: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?q=80&w=400&h=300&fit=crop",
    },
  ],
  applications: [
    {
      id: "a1",
      name: "Khayelitsha Youth Club",
      status: "approved",
      date: "2024-10-20",
      description: "Requesting sensor installation for clubhouse",
    },
  ],
  applicationForms: {
    volunteer: {
      id: "volunteer",
      title: "Volunteer with our field team",
      description: "Share your skills and availability so we can match you with nearby initiatives.",
      submitLabel: "Submit volunteer form",
      fields: [
        {
          id: "volunteer-full-name",
          label: "Full name",
          type: "text",
          placeholder: "Enter your full name",
          required: true,
        },
        {
          id: "volunteer-email",
          label: "Email address",
          type: "email",
          placeholder: "name@example.com",
          required: true,
        },
        {
          id: "volunteer-skills",
          label: "Primary skills",
          type: "textarea",
          placeholder: "Tell us how you would like to help",
          required: true,
        },
      ],
      submissions: [
        {
          id: "volunteer-sub-1",
          submittedAt: "2025-02-10T08:00:00Z",
          campaignId: "camp-water-resilience",
          status: "reviewing",
          values: {
            "volunteer-full-name": "Lerato Adams",
            "volunteer-email": "lerato@example.org",
            "volunteer-skills": "Weekend event check-in and supporter outreach",
          },
        },
      ],
    },
    help: {
      id: "help",
      title: "Apply for support",
      description: "Tell us what support is needed so our team can review and respond quickly.",
      submitLabel: "Send support request",
      fields: [
        {
          id: "help-full-name",
          label: "Contact person",
          type: "text",
          placeholder: "Name of the contact person",
          required: true,
        },
        {
          id: "help-phone",
          label: "Phone number",
          type: "phone",
          placeholder: "Best number to reach you",
          required: true,
        },
        {
          id: "help-support-type",
          label: "Support needed",
          type: "select",
          placeholder: "Select support type",
          required: true,
          options: ["Water access", "Community equipment", "Education program", "Emergency support"],
        },
        {
          id: "help-details",
          label: "Tell us more",
          type: "textarea",
          placeholder: "Share your request details",
          required: true,
        },
      ],
      submissions: [
        {
          id: "help-sub-1",
          submittedAt: "2025-02-12T10:30:00Z",
          campaignId: "camp-water-resilience",
          status: "new",
          values: {
            "help-full-name": "Mpho Ndlovu",
            "help-phone": "+27 82 123 4567",
            "help-support-type": "Water access",
            "help-details": "Requesting support for leak detection at community center",
          },
        },
      ],
    },
    sponsor: {
      id: "sponsor",
      title: "Partner or sponsor this mission",
      description: "Share your organization details and preferred tier to begin sponsorship planning.",
      submitLabel: "Send partner request",
      fields: [
        {
          id: "sponsor-organization",
          label: "Organization name",
          type: "text",
          placeholder: "Enter organization name",
          required: true,
        },
        {
          id: "sponsor-email",
          label: "Business email",
          type: "email",
          placeholder: "team@organization.com",
          required: true,
        },
        {
          id: "sponsor-contact-person",
          label: "Contact person",
          type: "text",
          placeholder: "Full name of partnership contact",
          required: true,
        },
        {
          id: "sponsor-bank-account",
          label: "Bank account details",
          type: "textarea",
          placeholder: "Account holder, bank, account number, branch code",
          required: true,
        },
        {
          id: "sponsor-tier",
          label: "Preferred tier",
          type: "select",
          placeholder: "Choose a tier",
          required: true,
          options: ["Community Partner", "Growth Partner", "Anchor Partner"],
        },
        {
          id: "sponsor-notes",
          label: "Partnership goals",
          type: "textarea",
          placeholder: "What outcomes are you targeting?",
          required: false,
        },
      ],
      submissions: [
        {
          id: "sponsor-sub-1",
          submittedAt: "2025-02-14T14:45:00Z",
          campaignId: "camp-water-resilience",
          status: "approved",
          values: {
            "sponsor-organization": "Blue River Holdings",
            "sponsor-email": "impact@blueriver.com",
            "sponsor-contact-person": "Nadia Jacobs",
            "sponsor-bank-account": "Blue River Holdings | FNB | 62100455210 | 250655",
            "sponsor-tier": "Growth Partner",
            "sponsor-notes": "Interested in long-term district-level support.",
          },
        },
      ],
    },
  },
  volunteers: [
    {
      id: "vol-1",
      fullName: "Lerato Adams",
      email: "lerato@example.org",
      phone: "+27 82 000 1001",
      skills: "Weekend check-in and supporter outreach",
      status: "available",
    },
    {
      id: "vol-2",
      fullName: "Thabo Mena",
      email: "thabo@example.org",
      phone: "+27 82 000 1002",
      skills: "Logistics, setup, and event floor support",
      status: "assigned",
    },
  ],
  campaigns: [
    {
      id: "camp-water-resilience",
      slug: "urban-water-resilience-2024",
      name: "Urban Water Resilience 2024",
      description: "Deploying smart-grid water sensors across high-density housing projects.",
      lifecycleStatus: "active",
      preset: "hybrid",
      allowsDirectDonations: true,
      allowsFundraisers: true,
      fundraisers: [
        {
          id: "fund-guguletu-water-grid",
          campaignId: "camp-water-resilience",
          slug: "guguletu-water-grid",
          title: "Guguletu Smart Grid Rollout",
          summary: "Install and maintain 500 water leak sensors for high-risk districts.",
          story:
            "This fundraiser equips field teams with diagnostic sensors and training for sustained leak prevention.",
          goal: 45000,
          raised: 28450,
          heroImage:
            "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&q=80&w=1200&h=675",
          status: "active",
        },
        {
          id: "fund-school-water-protection",
          campaignId: "camp-water-resilience",
          slug: "school-water-protection",
          title: "School Water Protection Fund",
          summary: "Reduce water disruptions for schools through resilient infrastructure upgrades.",
          story:
            "Focused upgrades across school sites keep classrooms running and improve long-term community access.",
          goal: 30000,
          raised: 7200,
          heroImage:
            "https://images.unsplash.com/photo-1497486751825-1233686d5d80?q=80&w=1200&auto=format&fit=crop",
          status: "active",
        },
      ],
      events: [
        {
          id: "camp-event-1",
          title: "Water Walk Gala 2024",
          date: "2024-11-12T18:00:00Z",
          endDate: "2024-11-12T22:00:00Z",
          venue: "V&A Convention Centre",
          address: "Dock Road, Victoria & Alfred Waterfront, Cape Town, 8001",
          description:
            "An evening of live music, donor recognition, and a keynote on urban water resilience.",
          campaignId: "camp-water-resilience",
          fundraiserId: "fund-guguletu-water-grid",
          volunteerIds: ["vol-2"],
          image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&fit=crop",
          capacity: 200,
          rsvpCount: 147,
          status: "completed",
          category: "gala",
          contactEmail: "events@thriveafrica.org",
        },
        {
          id: "camp-event-2",
          title: "Community Hackathon",
          date: "2024-12-05T09:00:00Z",
          endDate: "2024-12-05T17:00:00Z",
          venue: "Innovation Hub Guguletu",
          address: "12 NY 1, Guguletu, Cape Town, 7750",
          description:
            "A day-long hackathon for local developers and engineers to prototype smart-water solutions.",
          campaignId: "camp-water-resilience",
          fundraiserId: "fund-guguletu-water-grid",
          image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=800&fit=crop",
          capacity: 60,
          rsvpCount: 52,
          status: "completed",
          category: "hackathon",
          contactEmail: "tech@thriveafrica.org",
        },
      ],
      mediaPosts: [
        {
          id: "camp-media-1",
          title: "Scaling Smart Sensors in Q4",
          excerpt: "How ultrasonic waves are helping us find water leaks without digging.",
          content: "Technical deep dive into the IoT stack...",
          date: "Oct 28, 2024",
          author: "Dr. Sarah Jones",
          campaignId: "camp-water-resilience",
          fundraiserId: "fund-guguletu-water-grid",
          image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=400&h=300&fit=crop",
        },
      ],
      donations: [
        {
          id: "camp-dn-1",
          donorName: "Sarah Miller",
          amount: 50,
          date: "2024-03-20",
          campaignId: "camp-water-resilience",
          fundraiserId: "fund-guguletu-water-grid",
          channel: "direct",
          certificateGenerated: true,
        },
        {
          id: "camp-dn-2",
          donorName: "David Chen",
          amount: 100,
          date: "2024-03-21",
          campaignId: "camp-water-resilience",
          fundraiserId: "fund-guguletu-water-grid",
          channel: "social",
          certificateGenerated: true,
        },
      ],
      partnerPoolDonations: [
        {
          id: "camp-pool-dn-1",
          donorName: "EcoFlow Solutions",
          amount: 18500,
          date: "2025-11-21",
          campaignId: "camp-water-resilience",
          channel: "partner",
          certificateGenerated: true,
        },
      ],
      partnerPool: {
        totalPartnerDonations: 18500,
        totalAllocated: 0,
        balance: 18500,
        policy: {
          currency: "ZAR",
          rollingWindowDays: 30,
          lowMax: 10000,
          mediumMax: 50000,
          highMax: 150000,
        },
        allocations: [],
      },
    },
    {
      id: "camp-ecosystem-restoration",
      slug: "ecosystem-restoration-initiative",
      name: "Ecosystem Restoration Initiative",
      description: "General environmental restoration and long-term habitat resilience.",
      lifecycleStatus: "completed",
      preset: "general",
      allowsDirectDonations: true,
      allowsFundraisers: false,
      fundraisers: [],
      events: [],
      mediaPosts: [],
      donations: [],
      partnerPoolDonations: [],
      partnerPool: {
        totalPartnerDonations: 0,
        totalAllocated: 0,
        balance: 0,
        policy: {
          currency: "ZAR",
          rollingWindowDays: 30,
          lowMax: 10000,
          mediumMax: 50000,
          highMax: 150000,
        },
        allocations: [],
      },
    },
  ],
  activeCampaignId: "camp-water-resilience",
  activeFundraiserId: "fund-guguletu-water-grid",
  donations: [
    {
      id: "tx-101",
      donorName: "Sarah Miller",
      amount: 50,
      date: "2024-03-20",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      channel: "direct",
      certificateGenerated: true,
    },
    {
      id: "tx-102",
      donorName: "David Chen",
      amount: 100,
      date: "2024-03-21",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      channel: "social",
      certificateGenerated: true,
    },
    {
      id: "tx-103",
      donorName: "Mark Johnson",
      amount: 25,
      date: "2024-03-22",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      channel: "qrCode",
      certificateGenerated: true,
    },
    {
      id: "tx-104",
      donorName: "Emily Watson",
      amount: 500,
      date: "2024-03-23",
      campaignId: "camp-water-resilience",
      fundraiserId: "fund-guguletu-water-grid",
      channel: "direct",
      certificateGenerated: true,
    },
  ],
  tiers: [
    { id: "1", amount: 10, label: "The Drop", description: "Sensor maintenance for one week." },
    { id: "2", amount: 50, label: "The Stream", description: "One residential sensor kit." },
    { id: "3", amount: 250, label: "The River", description: "Technician apprenticeship for a month." },
    { id: "4", amount: 1000, label: "The Ocean", description: "Solar-power backup for a district hub." },
  ],
  pageCustomizations: {
    landing: {
      navigationLabel: "Home",
      heading: "Urban Water Resilience 2024",
      subheading: "Deploying smart-grid water sensors across high-density housing projects.",
      heroImage:
        "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&q=80&w=1200&h=675",
      isVisible: true,
      sections: [
        {
          id: "landing-sec-1",
          title: "Neighborhood-first deployment",
          description: "Sensors are prioritised for communities with long-standing supply instability.",
          image:
            "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "View rollout map",
        },
        {
          id: "landing-sec-2",
          title: "Auditable donor impact",
          description: "Every funded unit maps to a deployment record and audit-ready certificate flow.",
          image:
            "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "Open impact dashboard",
        },
      ],
    },
    fundraisers: {
      navigationLabel: "Fundraisers",
      heading: "Discover active fundraisers within this campaign",
      subheading: "Choose a fundraiser page with its own story, goal, events, and media coverage.",
      heroImage:
        "https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=1200&auto=format&fit=crop",
      isVisible: true,
      sections: [
        {
          id: "fundraisers-sec-1",
          title: "Fundraiser-led progress updates",
          description: "Each fundraiser can share transparent progress and evidence-backed milestones.",
          image:
            "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "View fundraisers",
        },
      ],
    },
    events: {
      navigationLabel: "Events",
      heading: "Field activations and donor engagement events",
      subheading: "Keep supporters close to the work with transparent event programming.",
      heroImage:
        "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop",
      isVisible: true,
      sections: [
        {
          id: "events-sec-1",
          title: "On-site demonstrations",
          description: "Live demonstrations explain sensor diagnostics and infrastructure priorities.",
          image:
            "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "Reserve seats",
        },
      ],
    },
    blog: {
      navigationLabel: "Media",
      heading: "Updates, evidence, and transparent reporting",
      subheading: "Stay current on milestones, policy shifts, and deployment transparency.",
      heroImage:
        "https://images.unsplash.com/photo-1504711331083-9c895941bf81?q=80&w=1200&auto=format&fit=crop",
      isVisible: true,
      sections: [
        {
          id: "blog-sec-1",
          title: "Monthly impact memo",
          description: "A concise operations memo for supporters, partners, and compliance teams.",
          image:
            "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "Read this month",
        },
      ],
    },
    partners: {
      navigationLabel: "Partners",
      heading: "Strategic partners that scale delivery",
      subheading: "Tiered partnerships with clear commitments, benefits, and public recognition.",
      heroImage:
        "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
      isVisible: true,
      sections: [
        {
          id: "partners-sec-1",
          title: "Mention-ready partner wall",
          description: "Spotlight trusted partners with narrative mentions tied to outcomes.",
          image:
            "https://images.unsplash.com/photo-1556155092-490a1ba16284?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "Meet current partners",
        },
      ],
    },
    apply: {
      navigationLabel: "Apply",
      heading: "Apply to volunteer, request support, or sponsor this mission",
      subheading: "Choose the application path that fits your goal and submit in minutes.",
      heroImage:
        "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop",
      isVisible: true,
      sections: [
        {
          id: "apply-sec-1",
          title: "Three paths, one simple process",
          description: "Volunteer, request help, or start a sponsorship conversation through dedicated application flows.",
          image:
            "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "Start application",
        },
      ],
    },
  },
};
